#!/bin/sh
export BE_HOME=/usr/local/tibco_be/be/5.2
export BE_WS=/Users/yxu/Developer/tibco/test_tutorial

${BE_HOME}/bin/be-engine --propFile be-engine.tra --propVar jmx_port=9899 -u default -c ${BE_WS}/FraudDetectionCache/fdcache.cdd fdcache.ear

